Repository google/auto, pull requests merged in 2019-10, with the labels that each got.

#767 Moe Sync
  value/userguide/builders-howto.md
Labels: cla: yes, internal-sync

#768 Add build status badge to the README.
  README.md
Labels: cla: yes

#769 Moe Sync
  service/annotations/pom.xml
Labels: cla: yes, internal-sync

#770 Moe Sync
  value/pom.xml
  value/processor/pom.xml
  value/src/it/functional/pom.xml
Labels: cla: yes, internal-sync

#774 Moe Sync
  value/src/main/java/com/google/auto/value/extension/AutoValueExtension.java
  value/src/main/java/com/google/auto/value/processor/AutoValueProcessor.java
  value/src/main/java/com/google/auto/value/processor/ExtensionContext.java
  value/src/test/java/com/google/auto/value/processor/ExtensionTest.java
Labels: cla: yes, internal-sync

#776 Moe Sync
  common/src/main/java/com/google/auto/common/BasicAnnotationProcessor.java
  common/src/main/java/com/google/auto/common/GeneratedAnnotationSpecs.java
  common/src/main/java/com/google/auto/common/MoreTypes.java
Labels: cla: no, internal-sync

#779 Moe Sync
  service/README.md
  value/userguide/index.md
Labels: cla: yes, internal-sync

#781 Moe Sync
  common/src/main/java/com/google/auto/common/AnnotationValues.java
  common/src/test/java/com/google/auto/common/AnnotationValuesTest.java
Labels: cla: yes, internal-sync

#782 MOE Sync 2019-10-30
  factory/src/main/java/com/google/auto/factory/processor/AutoFactoryProcessor.java
Labels: cla: yes, internal-sync
